// Multi-tenant configs - updated: 2025-11-01T08:05:29.779Z
// DO NOT EDIT MANUALLY - Run 'node sync-config.js' to update from Google Sheets
window.REVIEW_CONFIGS = {
  "beauty-bar": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "friseur-struwwelpeter-struwwelmobil-inh-e-immesberger": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "giarrizzo-franco": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "haarlequeen-in-der-beautybar": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "hilde-dietz-frisr": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "annemarie-osterhammel-friseursalon": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "bedburg-barbershop": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "elisabeth-schmitz-friseursalon": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "friseur-daulat": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "friseur-gudrun-meuter": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "friseursalon-anke-krichel": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "haaraktuell-inh-v-khn": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "haarstyling-esser-uerlings": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "hair-style-by-ferrand-elsdorf": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "hairexpress-friseur-real-bedburg": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "haircreation-jennifer-wien": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "jr-cut-color": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "sr-cut-color": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "salon-kcher": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "sara-rosa-friseurmeisterin": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "style-in-lounge-inh-reyhan-leu": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "wellness-therapeut-andreas-rudi": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  },
  "bahaarmas-by-linas-gbr": {
    "name": "",
    "category": "",
    "place_id": "",
    "google_maps_url": "",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": false,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": false,
    "referral_message": "Invite your friends to also leave a review and get their own discount!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": ""
  }
};

// Resolve slug from URL and set the active config
(function() {
  const resolveSlug = () => {
    const qp = new URL(window.location.href).searchParams.get("biz");
    if (qp) return qp.toLowerCase();
    
    const parts = window.location.hostname.split(".");
    if (parts.length > 2) {
      const subdomain = parts[0].toLowerCase();
      if (!subdomain.match(/^[a-z]+-[a-z0-9]+-[a-z0-9]+$/)) {
        return subdomain;
      }
    }
    
    return "default";
  };
  
  const slug = resolveSlug();
  window.REVIEW_TOOL_CONFIG = window.REVIEW_CONFIGS[slug] || window.REVIEW_CONFIGS["default"];
  console.log(`Config loaded for slug: ${slug}`, window.REVIEW_TOOL_CONFIG);
})();
