// Multi-tenant configs - updated: 2025-11-04T23:10:07.188Z
// DO NOT EDIT MANUALLY - Run 'node sync-config.js' to update from Google Sheets
window.REVIEW_CONFIGS = {
  "bodenseebaer": {
    "place_id": "ChIJaZc9cvD5mkcRHmSTH6v93-s",
    "name": "Bodenseebär in Hagnau",
    "category": "Kram",
    "google_maps_url": "https://www.google.com/maps/place/Bodenseeb%C3%A4r/@47.6741955,9.3156699,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipPzJOi4MgvmLLhTroCMcYW7TspmEwuNIDyEzZpS!2e10!3e12!6shttps:%2F%2Flh3.googleusercontent.com%2Fp%2FAF1QipPzJOi4MgvmLLhTroCMcYW7TspmEwuNIDyEzZpS%3Dw114-h86-k-no!7i1600!8i1204!4m11!1m2!2m1!1sbodensee+b%C3%A4r+hagnau!3m7!1s0x479af9f0723d9769:0xebdffdab1f93641e!8m2!3d47.674195!4d9.3158409!10e5!15sChRib2RlbnNlZSBiw6RyIGhhZ25hdVoWIhRib2RlbnNlZSBiw6RyIGhhZ25hdZIBBXN0b3JlmgEjQ2haRFNVaE5NRzluUzBWSlEwRm5UVU5KYTB4dWJVOTNFQUXgAQD6AQUIkAEQEg!16s%2Fg%2F11tw_st1pj?entry=ttu&g_ep=EgoyMDI1MTAyMi4wIKXMDSoASAFQAw%3D%3D",
    "hero_image": "https://lh3.googleusercontent.com/p/AF1QipPzJOi4MgvmLLhTroCMcYW7TspmEwuNIDyEzZpS=w408-h307-k-no",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "arthair": {
    "place_id": "ChIJoe44AXBPv0cRcpxEOwnFpb0",
    "name": "ArtHair",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJoe44AXBPv0cRcpxEOwnFpb0",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDymXJ3cLRq0mvo-DntZ1zoDLT8nvKvAh55dUPnxYvfqA02OMlJnojipOSp8nh4vd3LZVtPbBj_iKpoBFHJm677tcWeQnm8NMM5vOjC4cwcBfR-Nabju_1ZE12tGdgDRjbx61EqQEgx4k5lcQxM=s1600-w768",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "hairexpress-friseur-real-bedburg": {
    "place_id": "ChIJySq9pPBFv0cRUHwL6u8opjM",
    "name": "HairExpress Friseur real Bedburg",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJySq9pPBFv0cRUHwL6u8opjM",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDzehJxPLLu3lzzUtQVXRgvywFnY7amLrqPEJdDJjofXe4SUZn9RdhIoUvc0vMaigh4ph-Eub_ZlxkCqaRw0lRzcMIRKu9mVUC0IhQ8JfbsOKE6XHP0T9-x2nJW-S9z1BWNVXY6LadbGEXxRWhG4Rqpr=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "jr-cut-color": {
    "place_id": "ChIJXfToFZNPv0cRGC_JA1cnU9Q",
    "name": "JR | Cut & Color",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJXfToFZNPv0cRGC_JA1cnU9Q",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqHRmNzGVSB9ry6I6Urhfh4_4mMxZGS8XmpZJxZa8hCiiqJ_TgdV548Gg3to2DVzMtggZoPO7wEcR35y8lPUAjAr4coJLIItsMk=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "giarrizzo-franco": {
    "place_id": "ChIJK9Dp01hPv0cRcxWGk3HKOjw",
    "name": "Giarrizzo Franco",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJK9Dp01hPv0cRcxWGk3HKOjw",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDzulXwOG18ynNShEPmuxWChP5AAmg0S1otyA4x4vvMyHeIRMbmH6Tj4u49EBRP1SCnT0kVaH5TiUaAADy0hglKYL-dS8nQmmSfsqd4Tc2j45TcvDAOLgdISFSUbPiEfSym-J5v0_DX36TKVuQ=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "haarlequeen-in-der-beautybar": {
    "place_id": "ChIJm3FoNjxPv0cRhMiJ1waiSw8",
    "name": "Haarlequeen in der \"BeautyBAR\"",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJm3FoNjxPv0cRhMiJ1waiSw8",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqFk-XHhTFzc9o35jbCOmvnQVGF5JrGWv5eEDFSmOpdSH5aScLfFMnW_O20v63_2aBAaCOIkEm9ZyzlBlnEOt_7BSWJViXSxDLI=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "style-in-lounge-inh-reyhan-leu": {
    "place_id": "ChIJKTeufldPv0cRrlPMWVbjN-I",
    "name": "Style in lounge Inh. Reyhan Leu",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJKTeufldPv0cRrlPMWVbjN-I",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDwzXQoBdwU2EigotIq2f7-k5dUa1MCAAeB0HpVIK8d9FckaRWHYstAzchnU1rfmfjbM0TJIdDstXvW3nLQSOQ2qfRidiHx5JAQ6orlTfQvGvif6kvDmRQ6xWv_zwHsdWd_cM4UaW63dsv97DA=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "bahaarmas-by-linas-gbr": {
    "place_id": "ChIJW7JFF9xPv0cR-qXwlA9fdR0",
    "name": "baHAARmas by Lina's GbR",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJW7JFF9xPv0cR-qXwlA9fdR0",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDzqnTH3DvOHceaW5TgCZ0KsL2CnmHOVpk0o54V4vidLVcA4I7YKyy8Z_MJMMth7T-EiO-R7qC1jYMYK9oBbCDRIKC7YJTLeApzmaxHgvsP43pPD5JJXfXvZE4TswSbsp3_KSzE40MPNqZ_Y=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "bedburg-barbershop": {
    "place_id": "ChIJ5Q6IZNZFv0cRrF2l7-tjPLg",
    "name": "Bedburg Barbershop",
    "category": "Hair Care, Health",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJ5Q6IZNZFv0cRrF2l7-tjPLg",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDxQXIqe3I-qiIFirKQXK3PhMK_8I4Ol1p0yoqWeYJuViNbMCAgUFfOXaHgwwjudKzd7Y8aMnc3-Yn9GnUtrlv4hV39Mrm2rs8TGPKqD9ldaILs6W4tBDYb9E0tWL0OdZPu3v3_d16BBnFB4aPZnevoJ=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "friseur-daulat": {
    "place_id": "ChIJBb1o3PdFv0cRS4OImlpsZq0",
    "name": "Friseur Daulat",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJBb1o3PdFv0cRS4OImlpsZq0",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqElrBUUAY3aA6aCiRzhP5ZSkvv0lTBtUkkxx6aw0uUrJ2Zhmt8ak3rvKmAnJsv8Oq3p58l6e5itcGHqZwpWpPpun_bc_Lz56UE=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "elisabeth-schmitz-friseursalon": {
    "place_id": "ChIJZaf3wmRPv0cR-fKXYH4w-xE",
    "name": "Elisabeth Schmitz Friseursalon",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJZaf3wmRPv0cR-fKXYH4w-xE",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "beauty-bar": {
    "place_id": "ChIJqUvS_4xPv0cRIavCzkVDbEo",
    "name": "Beauty BAR",
    "category": "Beauty Salon, Hair Care, Spa, Store",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJqUvS_4xPv0cRIavCzkVDbEo",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqH7i8TKR5F9v1l1wuhJpyIAhQamrrPcvMEwz2xHwgi5mYs5kbF_sDX5hOq9jyKh6VrU6ACzbI89ZVqvauBftaKxurVMhT7YyFE=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "hilde-dietz-frisr": {
    "place_id": "ChIJp2r2D1dPv0cRddq-Ht7makU",
    "name": "Hilde Dietz Frisör",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJp2r2D1dPv0cRddq-Ht7makU",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqHQ-9go_L7AVoZ1f1nwJ-MMa6mfAeya3yJaefJv2DJXX6y4ZWBH5bD6m3tCOXcCkt9S5_NbguYXMIelsAzr6ro-FoVGx2pxmog=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "friseur-struwwelpeter-struwwelmobil-inh-e-immesberger": {
    "place_id": "ChIJW1IBvPdFv0cR1s07Add3aEU",
    "name": "Friseur Struwwelpeter / Struwwelmobil Inh.: E. Immesberger",
    "category": "Hair Care, Store",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJW1IBvPdFv0cR1s07Add3aEU",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "salon-kcher": {
    "place_id": "ChIJf2FGfF9Pv0cRpdqw01_ROOU",
    "name": "Salon Köcher",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJf2FGfF9Pv0cRpdqw01_ROOU",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "friseur-gudrun-meuter": {
    "place_id": "ChIJsxGjD29Pv0cRFAe29G434u8",
    "name": "Friseur Gudrun Meuter",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJsxGjD29Pv0cRFAe29G434u8",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "wellness-therapeut-andreas-rudi": {
    "place_id": "ChIJn8LnAfdFv0cR9oh2o7EVPF4",
    "name": "Wellness Therapeut Andreas Rudi",
    "category": "Beauty Salon, Hair Care, Spa",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJn8LnAfdFv0cR9oh2o7EVPF4",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqFZdlmp6SADpDnB05Ka3VnVaC2x-c9scebVWzk4bMZohJmlVRjmqneEEA-if2CPLdzNge17-SaepYdlhcbNkCIG7UYONBFPPng=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "friseursalon-anke-krichel": {
    "place_id": "ChIJjdOsC3BPv0cRgbq_kiVrPC4",
    "name": "Friseursalon Anke Krichel",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJjdOsC3BPv0cRgbq_kiVrPC4",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDyO4cjxVyjY-ZR0M37DUzaXD5TrB9EXB2q8loUtdpZ3_p9_6NAHe9gbUFSHF7ocU4BH889gXPa6DNEro0OadZ_1EgLkHM-uAavX0ZY0AYpNggN8Zab2Ht-6PBEIUziyupQjk6weqdJTQEnGvQ=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "annemarie-osterhammel-friseursalon": {
    "place_id": "ChIJV1oFoexFv0cRdLmEeKReyng",
    "name": "Annemarie Osterhammel Friseursalon",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJV1oFoexFv0cRdLmEeKReyng",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "haircreation-jennifer-wien": {
    "place_id": "ChIJddwpW4JPv0cR5BrNN5yhc5k",
    "name": "Haircreation Jennifer Wien",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJddwpW4JPv0cR5BrNN5yhc5k",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "sara-rosa-friseurmeisterin": {
    "place_id": "ChIJwbbTR1RFv0cRCGkiCnLz1zY",
    "name": "Sara Rosa Friseurmeisterin",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJwbbTR1RFv0cRCGkiCnLz1zY",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqEbiSofgPM-I1JPy3IeSXyUwlHMx6x5nRYUiZZ1HXb2W_qIcQX2MOvNq_xF9ld14JWUYvfhIJ2WZbCx_IJyLfXtFls-HHta8gE=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "hairloft98": {
    "place_id": "ChIJM9V4cQxMv0cRdKqfUXTBXJA",
    "name": "HairLoft98",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJM9V4cQxMv0cRdKqfUXTBXJA",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqFZdHrbyFjZf-RDzrr8pJ1y2VbGpGkhDP7o1V0xtYZc3BwMMxgrBxVRyxKOM-W--nkvktmZmPnpcR4WXyyllyM71h4rDFadg9c=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "viola-haardesign": {
    "place_id": "ChIJzTVxtwJNv0cRaGhHaGYY0nM",
    "name": "VIOLA HAARDESIGN",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJzTVxtwJNv0cRaGhHaGYY0nM",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqEQ4HiJZdOl-Cnf3ab2uMcGJ-_ZyTYwOiRx0-RPmeH_Ia0T4QDjdfmoYd5MmxaQLAo1jl6qF8zj8gHJBgR9wC7BkKJ21PaOi0c=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "happy-hair": {
    "place_id": "ChIJWboukUNMv0cR54Bh_mgI048",
    "name": "Happy Hair",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJWboukUNMv0cR54Bh_mgI048",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDxWnQ34vq1TqllQJWX4b5JcfBPIU-wXVnJOTC8alKiLsUVU23FN2WNzYPdbcaoZj6_3SSeN8qzCuVK0wjs7V2zuAgX3EPVgMw0-oqekp_9E08V_RTqgYRHiFKZzZ3smNxEgJHhh2Ym5rkuDxTU=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "topstyle-haarstudio": {
    "place_id": "ChIJB2SVoDNMv0cR0LdZtWeHC3I",
    "name": "Topstyle Haarstudio",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJB2SVoDNMv0cR0LdZtWeHC3I",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDzMG-5GfhGdcv2-CHDpJJAluMcmfb-QCs0pyAwPJkh_hD75LPrNUKLZy7u68HIPl7GcXIJLbFfgZlpvDOVZRPKwDfRoGDp6wEv75p_GiVSjkezz-0b_Fo8s6LV3rqvogay0eAJTWavn2vs3LA=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "manu-factur": {
    "place_id": "ChIJk3Z8fxdMv0cRvIdziRemjFw",
    "name": "manu-factur",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJk3Z8fxdMv0cRvIdziRemjFw",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqHY9xNsM68Ebu72LGvgO6rTQuFRixA_A36dPSmqSPogsSV-3e4XoGZSetpfz9ke-eQ17Kd21fNs12o6PX17XhBMgHl3KdrEa6w=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "lockenwunder-ffnungszeiten-nur-nach-terminvereinbarung": {
    "place_id": "ChIJ-3IzV8pLv0cRFVjoUAMFPEY",
    "name": "Lockenwunder | Öffnungszeiten nur nach Terminvereinbarung",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJ-3IzV8pLv0cRFVjoUAMFPEY",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqFGHvsWbUTR7uPXIS7uxYghZPnsAK_k5OTrfJCCJMkWvunR_QbGVmYd9uzP_dBj__Rt2L5wACO9wyHB1P_xOh9yVrCBTxv3vAE=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "hair-and-beauty-lounge-de-boer": {
    "place_id": "ChIJPx5mAIJPv0cR89UFUoxDLjg",
    "name": "Hair and Beauty Lounge De Boer",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJPx5mAIJPv0cR89UFUoxDLjg",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqH1BxzPCBs_Iff5Z1fZHvLdDty6itrFmYKlRNwiKg5XcSZ4Nvguu4X3hMk6VM4jMXj6-0_hWtXOd2-s66BCiyY8eSb1G3iaHQ=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "harry-chrie": {
    "place_id": "ChIJR0EDDAhNv0cRAerkaHQ6yCs",
    "name": "Harry & Chérie",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJR0EDDAhNv0cRAerkaHQ6yCs",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDwrKKnzNhzy4jpa4A8aF49E18hBG3INN3W7f0aGEwK8f_KgPXDT1cfUfPAxTDHR766yjP84zatUaekjQaxw_Y3o_eSzntpd84HxwMspS40X9Kec7l4UHKnLU46-uolIYRQsCYaO52Tm8IYxMQ=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "m-c-haarwerk": {
    "place_id": "ChIJh9QfL8VLv0cRZSdeUv1MQ_o",
    "name": "M & C Haarwerk",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJh9QfL8VLv0cRZSdeUv1MQ_o",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqG-7vMNPUMWmgrFC4pZykENcSHaePSvLYFuvswTxDXryT8733d-cXDNrEMXG_kKVBCoR9CaM2OCYdKjTzhEr7VEj54ZOm7ifrE=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "friseursalon-esra": {
    "place_id": "ChIJbcv9WwBMv0cRjgZn8PPRchk",
    "name": "Friseursalon Esra",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJbcv9WwBMv0cRjgZn8PPRchk",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "top-hair-moden-inh-antje-stollenwerk": {
    "place_id": "ChIJS9wiGddOv0cRfuhqop6VSko",
    "name": "Top Hair Moden - Inh. Antje Stollenwerk",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJS9wiGddOv0cRfuhqop6VSko",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqEER8TBR2Irqi6HHFrYqMkVtxndLUDL5aaFcOkhudHqQkF0ifXslgECSOJaCgsgkCy8Id8MuZ7TYlBRZZpQ9yT96N4diFU7J9I=s1600-w450",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "bel-hair-frisuren": {
    "place_id": "ChIJuewq6vpNv0cRlTuD-rFGfxc",
    "name": "Bel Hair Frisuren",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJuewq6vpNv0cRlTuD-rFGfxc",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqEqJyr658P3EH9wyI6AqtxwLKqQqN38q_iWH4PSzFZ5oK3ZXoaz03eNhEX1Yv40AjjibHCoqR_5EPs5z5fyFNK2WqVYAMRqyXs=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "ambiente-haarstudio": {
    "place_id": "ChIJBRKYo4hLv0cRPq8JgDs848s",
    "name": "Ambiente Haarstudio",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJBRKYo4hLv0cRPq8JgDs848s",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "friseursalon-first-class": {
    "place_id": "ChIJgcYqYzxMv0cR4YwwTIIrvaM",
    "name": "Friseursalon First Class",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJgcYqYzxMv0cR4YwwTIIrvaM",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqGONuscemYGh8CUkrBJxesT9QPyeti3wBfr8vsnPlaJOZliUD_dH_xRjIWJO0QY60_Yjf6B1c3pM8QLE2q-il0An8f33J6vcqY=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "haarstudio-polat": {
    "place_id": "ChIJ-aFXCzxMv0cR-LJqikUpCWM",
    "name": "Haarstudio Polat",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJ-aFXCzxMv0cR-LJqikUpCWM",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDzvE3LuS_csUneTGYkZgCwkyd8dea-YwlzUMIsdIe3a15Gj4T5hwZmcoRRnTp3wLN-zD6u_wr5NCk2LyE0sjHm38O17fzgTfSjTkIv2nZsH_S0n81ITxmPi0d_-gv9r0W1wNQgCxG4JgvK6eg=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "haarkult-by-cawo": {
    "place_id": "ChIJZXhojYhLv0cR6gVDtrMw558",
    "name": "HAARKULT by CaWo",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJZXhojYhLv0cR6gVDtrMw558",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "friseur-filz": {
    "place_id": "ChIJx0bn5ieXcUERdnNmkzVnUjc",
    "name": "Friseur Filz",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJx0bn5ieXcUERdnNmkzVnUjc",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDyVJEF-lTeWnBXROOgD4kNBtBwnsh5qxAmABvzZgc3wR-Iko0gSQvCaLl2FHP2R04hQE8zYdd7sHWYPVfvJ1gatHXE7jhH4yrLsXggnTF2gGvv7ZNTSEfU943Mww60oaaH1dVKE6MelT_sj0A=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "steinhauer-beauty-and-hair": {
    "place_id": "ChIJuSBmlPNLv0cRXgWcUEXJG1s",
    "name": "Steinhauer - Beauty and Hair",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJuSBmlPNLv0cRXgWcUEXJG1s",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqHQZ2hTywJ8pZXEACXwIcUH6HmkSmEqRC5COfxCWi06DX1tGkssXMid1YeQHAiU54KETndaxNd_K6bcXXrecfRvyxZguNfutF0=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "ivans-barbershop-grevenbroich": {
    "place_id": "ChIJbdOcfF5Nv0cREz4glKXhGwU",
    "name": "Ivan's Barbershop Grevenbroich",
    "category": "Hair Care, Health",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJbdOcfF5Nv0cREz4glKXhGwU",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDy01Ky1vMkd8aOS_HIEY_HgyKjlQdIdHITdTVKTv5JKC5QN4iI4TOw7q4hgNE9FGsGJN6pXRXaSge13xpv1Ea-B9wX813gKOWWgAUg2fMhIavP-9X_qI1_p77Sw4O3ec_5HevXs03t_bXTUcVk=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "heikes-hair-team": {
    "place_id": "ChIJ1c4-NVdNv0cRvFZm4sCnZrw",
    "name": "Heike's Hair Team",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJ1c4-NVdNv0cRvFZm4sCnZrw",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDydotk3owo5FzMc6sGkHvVz4Twl8d02oRcGWJvakYRP6408KgME0I6c1lLVGx4bdy3eTu0Veb36fGp0hRZHqHvQ5-BqWhqRSffeZRFog9D2TORlCYD7OkViTDjOj18jC82swib-9AAK9HjyZQ=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "kthe-aretz-friseursalon": {
    "place_id": "ChIJawpllZxOv0cRg83b7XZo_4o",
    "name": "Käthe Aretz Friseursalon",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJawpllZxOv0cRg83b7XZo_4o",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDyXRVx8rbfUveF_FBs7KHRtIR16G9Jk85Rz2t0JqIBAcpE8Qqxj_VkIs3qvbflOCH-mw1xEkfmqyVPgOlNgqz4bCaBIr_-8GPH5noub6AMuwNWGTrbLPbzlgk_aoA1kuk2gUu-vq_djk4JUrvg=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "cut-style-evelyn-martin": {
    "place_id": "ChIJSYY61XxLv0cRnM0lVKqu_bk",
    "name": "Cut & Style Evelyn Martin",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJSYY61XxLv0cRnM0lVKqu_bk",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqGmEJBKXMX-4aJTRkJ7sM80Xnw4-87Wmnt8QjIFrZu83f-VllJ2xv6nFR97uF4SZQtcTFobjLwihkkSfqrqFT7BbtAATLEAbw=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "heibel-friseursalon": {
    "place_id": "ChIJMcQIM_tKv0cRHNf03Jk1FHA",
    "name": "Heibel Friseursalon",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJMcQIM_tKv0cRHNf03Jk1FHA",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "billstein-haare": {
    "place_id": "ChIJ_3RrkhdMv0cR_BM-0paS_84",
    "name": "Billstein Haare",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJ_3RrkhdMv0cR_BM-0paS_84",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "hairstyle-msk": {
    "place_id": "ChIJz08bri9Mv0cRt7K59RAtI4Q",
    "name": "Hairstyle Müskü",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJz08bri9Mv0cRt7K59RAtI4Q",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "eleonore-elisabeth-elju-jungverdorben-friseur": {
    "place_id": "ChIJazzF8qVOv0cRADepK5y8wj4",
    "name": "Eleonore Elisabeth ElJu Jungverdorben Friseur",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJazzF8qVOv0cRADepK5y8wj4",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "steffis-haarstbchen-stefanie-daumen-friseur": {
    "place_id": "ChIJzZdJifRMv0cRG_t9hxgK034",
    "name": "Steffi’s Haarstübchen - Stefanie Daumen | Friseur",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJzZdJifRMv0cRG_t9hxgK034",
    "hero_image": "",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "frisr-thonet-grevenbroich": {
    "place_id": "ChIJAyH7kyuXcUERUpa8-5vzUKY",
    "name": "Frisör Thonet Grevenbroich",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJAyH7kyuXcUERUpa8-5vzUKY",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDySrCxjGCzzwYjbw5JhREQYE4YRFdpeQZ_Gm-SeJWzbGE21HnacT63xxC2xSdvY-xEW-FH1wNbR4-m_kuMCvDVDsEcr8pq5doLXBVCzNdKScmv2pgzo1SMNZ6hnpQqTeumu0JRf8pJ7Law6lQ=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "sonja-weihrauch-haarkunst": {
    "place_id": "ChIJ_Y9bOnxLv0cR5ySNisTzoQY",
    "name": "Sonja Weihrauch Haarkunst",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJ_Y9bOnxLv0cR5ySNisTzoQY",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqFmdy0SzLYSIyhqqpVBtuVQ2mGu4X6r-6YVIdD0_3DE_K4VZVfm9WtHkWjSY0dC4Ng-T4vjJYuG-A2GoTtPk3v8dXYTtLq7rYE=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "schnittpunkt-belkiz": {
    "place_id": "ChIJ0dwHa31Lv0cRQlBDGhJW0cQ",
    "name": "Schnittpunkt Belkiz",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJ0dwHa31Lv0cRQlBDGhJW0cQ",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDy0gL6NTf8Mac0de5G5eHK1JEm2qzyGFAaKo_kMPHwCh4blA88gWu65yYLeatWmIlqsrgdSatxJsYGyksRwKTICfwFkeoCsS4QCPaLf5_zMWZtu-3V-JUZld8oux6W05jTldKeP22dyi9wq-W8=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Lade deine Freunde ein sich Ihren eigenen Rabattcode zu holen!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  }
};

// Resolve slug from URL and set the active config
(function() {
  const resolveSlug = () => {
    const qp = new URL(window.location.href).searchParams.get("biz");
    if (qp) return qp.toLowerCase();
    
    const parts = window.location.hostname.split(".");
    if (parts.length > 2) {
      const subdomain = parts[0].toLowerCase();
      // Only ignore obvious Vercel auto-generated subdomains (long random alphanumeric hashes)
      // Allow all business slugs, including those with 3 segments like "friseursalon-anke-krichel"
      // Vercel pattern: very long segments (10+ chars) with numbers, like "abc123def456-ghi789jkl012-mno345pqr678"
      const isVercelPattern = /^[a-z0-9]{10,}-[a-z0-9]{10,}/.test(subdomain) && /\d/.test(subdomain);
      if (!isVercelPattern) {
        return subdomain;
      }
    }
    
    return "default";
  };
  
  const slug = resolveSlug();
  window.REVIEW_TOOL_CONFIG = window.REVIEW_CONFIGS[slug] || window.REVIEW_CONFIGS["default"];
  console.log(`Config loaded for slug: ${slug}`, window.REVIEW_TOOL_CONFIG);
})();
