// Multi-tenant configs - updated: 2025-11-13T07:11:38.286Z
// DO NOT EDIT MANUALLY - Auto-generated by admin API
window.REVIEW_CONFIGS = {
  "bodenseebaer": {
    "place_id": "ChIJaZc9cvD5mkcRHmSTH6v93-s",
    "name": "Bodenseebär in Hagnau",
    "category": "Store",
    "google_maps_url": "https://www.google.com/maps/place/Bodenseeb%C3%A4r/@47.6741955,9.3156699,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipPzJOi4MgvmLLhTroCMcYW7TspmEwuNIDyEzZpS!2e10!3e12!6shttps:%2F%2Flh3.googleusercontent.com%2Fp%2FAF1QipPzJOi4MgvmLLhTroCMcYW7TspmEwuNIDyEzZpS%3Dw114-h86-k-no!7i1600!8i1204!4m11!1m2!2m1!1sbodensee+b%C3%A4r+hagnau!3m7!1s0x479af9f0723d9769:0xebdffdab1f93641e!8m2!3d47.674195!4d9.3158409!10e5!15sChRib2RlbnNlZSBiw6RyIGhhZ25hdVoWIhRib2RlbnNlZSBiw6RyIGhhZ25hdZIBBXN0b3JlmgEjQ2haRFNVaE5NRzluUzBWSlEwRm5UVU5KYTB4dWJVOTNFQUXgAQD6AQUIkAEQEg!16s%2Fg%2F11tw_st1pj?entry=ttu&g_ep=EgoyMDI1MTAyMi4wIKXMDSoASAFQAw%3D%3D",
    "hero_image": "https://lh3.googleusercontent.com/p/AF1QipO4GZJ5CsQJdlprN6tE-dYSw6PGqMpkgYoHP-kX=w408-h305-k-no",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Invite your friends to get their own discount code!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "arthair": {
    "place_id": "ChIJoe44AXBPv0cRcpxEOwnFpb0",
    "name": "ArtHair",
    "category": "Hair Care",
    "google_maps_url": "https://www.google.com/maps/place/?q=place_id:ChIJoe44AXBPv0cRcpxEOwnFpb0",
    "hero_image": "https://lh3.googleusercontent.com/place-photos/AEkURDymXJ3cLRq0mvo-DntZ1zoDLT8nvKvAh55dUPnxYvfqA02OMlJnojipOSp8nh4vd3LZVtPbBj_iKpoBFHJm677tcWeQnm8NMM5vOjC4cwcBfR-Nabju_1ZE12tGdgDRjbx61EqQEgx4k5lcQxM=s1600-w768",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Invite your friends to get their own discount code!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "https://script.google.com/macros/s/AKfycbzUpM-SbvZNMclVht4Q4PuWqXxG7MfrPygjx-UJOP0GNh_bzU6bC1jl2bwqSBWjlM09uw/exec ",
    "min_review": 5
  },
  "the-coco-club": {
    "place_id": "ChIJ1_S1trA72jARF7oXy2uAU6U",
    "name": "The Coco Club",
    "category": "Cafe",
    "google_maps_url": "https://maps.google.com/?cid=11913006639782279703",
    "hero_image": "https://lh3.googleusercontent.com/places/ANXAkqFs2wo2WWOyZgatTQkZPPZ3w_qox_ogfxrjlLiy9-G3k4jHELGQBa5Cch5WWm2UfxTKbGjJQ9rDhIZSoQfBnxO7oELpZX4nG18=s1600-w800",
    "logo_url": "",
    "discount_enabled": true,
    "discount_percentage": 10,
    "discount_valid_days": 30,
    "referral_enabled": true,
    "referral_message": "Invite your friends to get their own discount code!",
    "google_review_base_url": "https://search.google.com/local/writereview?placeid=",
    "google_review_url": "",
    "sheet_script_url": "(optional, leave empty for now)",
    "min_review": 5
  }
};

// Resolve slug from URL and set the active config
(function() {
  const resolveSlug = () => {
    const qp = new URL(window.location.href).searchParams.get("biz");
    if (qp) return qp.toLowerCase();
    
    const parts = window.location.hostname.split(".");
    if (parts.length > 2) {
      const subdomain = parts[0].toLowerCase();
      // Only ignore obvious Vercel auto-generated subdomains (long random alphanumeric hashes)
      // Allow all business slugs, including those with 3 segments like "friseursalon-anke-krichel"
      // Vercel pattern: very long segments (10+ chars) with numbers, like "abc123def456-ghi789jkl012-mno345pqr678"
      const isVercelPattern = /^[a-z0-9]{10,}-[a-z0-9]{10,}/.test(subdomain) && /\d/.test(subdomain);
      if (!isVercelPattern) {
        return subdomain;
      }
    }
    
    return "default";
  };
  
  const slug = resolveSlug();
  window.REVIEW_TOOL_CONFIG = window.REVIEW_CONFIGS[slug] || window.REVIEW_CONFIGS["default"];
  console.log(`Config loaded for slug: ${slug}`, window.REVIEW_TOOL_CONFIG);
})();
